import Head from 'next/head'
import { useState } from 'react'




export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-200 flex justify-center items-center h-screen">
        <div className="bg-red-400 max-w-6xl w-full mx-auto h-[70vh] p-5 rounded-lg">
          {/* Messages */}
          <div className='h-[80%] bg-white my-2 rounded-lg'>

          </div>

          {/* Post */}
          <div className='flex flex-col gap-2'>
            <input type='file' value={message.img} onChange={(e) => setMessage({ ...message, text: e.target.value })} />
            <input type='text' className='w-full rounded-full px-5 py-2' placeholder='Type your message here...' value={message.text} onChange={(e) => setMessage({ ...message, text: e.target.value })} />
          </div>
        </div>

      </main>
    </>
  )
}
